//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class IST_Exception
    {
        public int ExceptionID { get; set; }
        public Nullable<int> SampleAliquotID { get; set; }
        public Nullable<int> AliquotLocationID { get; set; }
        public string UnknownAliquotID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> TrayID { get; set; }
        public Nullable<int> TubeLocation { get; set; }
        public string TubeGridLocation { get; set; }
        public Nullable<int> DrawerSlotID { get; set; }
        public Nullable<int> ExceptionTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> SuppressFlag { get; set; }
    }
}
