//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class IST_SessionUnknownSA_vw
    {
        public Nullable<int> SessionID { get; set; }
        public int ScanId { get; set; }
        public string TrayCode { get; set; }
        public int ScanDetailId { get; set; }
        public string AliquotID { get; set; }
        public Nullable<int> PositionNumber { get; set; }
        public string PositionText { get; set; }
    }
}
