//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class IST_SessionSampleAliquot_vw
    {
        public int SessionID { get; set; }
        public string SessionStatusID { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SampleID { get; set; }
        public Nullable<int> AliquotLocationID { get; set; }
        public Nullable<int> TrayID { get; set; }
        public Nullable<int> TubeLocation { get; set; }
        public string TubeGridLocation { get; set; }
        public int SampleAliquotID { get; set; }
        public string AliquotStatusID { get; set; }
        public string SampleAliquotStatusID { get; set; }
        public Nullable<int> UserCustodian { get; set; }
    }
}
