//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class IST_TrayType
    {
        public int TrayTypeID { get; set; }
        public string TrayDescription { get; set; }
        public Nullable<int> TrayCapacity { get; set; }
        public Nullable<int> TrayRows { get; set; }
        public Nullable<int> TrayColumns { get; set; }
    }
}
