//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class IST_AliquotLocation_vw
    {
        public int SampleAliquotID { get; set; }
        public string SampleID { get; set; }
        public string AliquotID { get; set; }
        public Nullable<int> SubtypeID { get; set; }
        public string SA_StatusID { get; set; }
        public Nullable<int> SA_SessionID { get; set; }
        public Nullable<int> TrayID { get; set; }
        public Nullable<int> TubeLocation { get; set; }
        public Nullable<int> UserCustodian { get; set; }
        public string AL_StatusID { get; set; }
        public Nullable<int> AL_SessionID { get; set; }
    }
}
