//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class IST_SessionSA_vw
    {
        public int SessionID { get; set; }
        public string SessionStatus { get; set; }
        public int SampleAliquotID { get; set; }
        public string AliquotID { get; set; }
        public string SAStatus { get; set; }
    }
}
