//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleTracking.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class IST_SampleAliquot
    {
        public int SampleAliquotID { get; set; }
        public string SampleID { get; set; }
        public string AliquotID { get; set; }
        public Nullable<int> SubtypeID { get; set; }
        public string StatusID { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual IST_SampleAliquot IST_SampleAliquot1 { get; set; }
        public virtual IST_SampleAliquot IST_SampleAliquot2 { get; set; }
    }
}
